### ISSUE TITLE
Implement EventsSource class

### ISSUE THREAD

**Issue by rexim** [tsoding/Issuestant#38]
Split from #20 

---

### Pieces
- [x] #43 GitHub events as a lazy stream
- [x] #47 Implement EventsSource.pollingIteration
- [x] #51 Unit Tests for EtagPolling
- [x] #48 Implement EventsSource.extractEvents
- [x] ~~#46 Get rid of wart suppress~~
